name: Xray Vless Reality Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Setting up the job..."

    - name: Install and run Xray
      run: |
        sudo mkdir -p /etc/xray
        sudo mkdir -p /var/log/xray
        curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh | bash

    - name: Configure Xray (VLESS Reality server)
      run: |
        UUID=$(cat /proc/sys/kernel/random/uuid)
        PORT=443

        openssl ecparam -name prime256v1 -genkey -noout > private.key
        PRIVATE_KEY=$(openssl ec -in private.key -text -noout | grep "priv:" -A 3 | tail -n 3 | tr -d '\n[:space:]')
        SHORT_ID=$(openssl rand -hex 8)

        cat > /etc/xray/config.json << EOF
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": $PORT,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "$UUID",
            "flow": "",
            "level": 0,
            "email": "user@example.com"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "www.google.com:443",
          "xver": 0,
          "serverNames": [
            "www.google.com"
          ],
          "privateKey": "$PRIVATE_KEY",
          "shortIds": [
            "$SHORT_ID"
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
EOF

        echo "UUID=$UUID" >> $GITHUB_ENV
        echo "PRIVATE_KEY=$PRIVATE_KEY" >> $GITHUB_ENV
        echo "SHORT_ID=$SHORT_ID" >> $GITHUB_ENV

    - name: Start Xray
      run: |
        sudo nohup xray run -config /etc/xray/config.json &

    - name: Show connection info
      run: |
        sleep 5
        echo "VLESS Reality Connection Info:"
        echo ""
        echo "vless://$UUID@$(curl -s ifconfig.me):443?encryption=none&flow=&security=reality&sni=www.google.com&fp=randomized&pbk=$PRIVATE_KEY&sid=$SHORT_ID&type=tcp&headerType=none#RealityServer"
